server {
    listen 8080;
    root /usr/share/nginx/html;
    charset utf-8;
    types {
        application/json json;
        application/geo+json geojson;
        text/csv csv;
        text/plain txt;
    }
    gzip on;
    gzip_types application/json application/geo+json text/csv text/plain;
    gzip_min_length 1024;
    location = /health { return 200 'ok'; }
    location / {
        add_header Cache-Control "public, max-age=3600";
        try_files $uri =404;
    }
}
