(() => {
  const $=id=>document.getElementById(id),reduced=matchMedia('(prefers-reduced-motion: reduce)');
  let current=null,enabled=true,open=false,sound=false,ctx=null,master=null,sources=[],soundTimer=0,soundVersion=0,hideTimer=0,sceneVersion=0;
  const art=(el,id)=>{const n=id%9;el.classList.toggle('interest-art',id>=9);el.style.setProperty('--sx',(n%3)*50+'%');el.style.setProperty('--sy',Math.floor(n/3)*50+'%');};
  function stopSound(){soundVersion++;clearInterval(soundTimer);sources.forEach(s=>{try{s.stop()}catch{}});sources=[];if(master){master.disconnect();master=null;}}
  function tone(hz,when,duration,volume=.025){if(!ctx||!master)return;const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=hz;g.gain.setValueAtTime(0,when);g.gain.linearRampToValueAtTime(volume,when+.025);g.gain.exponentialRampToValueAtTime(.0001,when+duration);o.connect(g).connect(master);o.start(when);o.stop(when+duration+.02);o.onended=()=>{o.disconnect();g.disconnect();};}
  async function playSound(){stopSound();if(!sound||!open||!current)return;try{ctx ||= new (window.AudioContext||window.webkitAudioContext)();const version=soundVersion;await ctx.resume();if(!open||!sound||version!==soundVersion)return;master=ctx.createGain();master.gain.value=.18;master.connect(ctx.destination);const type=window.MEMORY_SCENES[current.id].ambiance;
      const buffer=ctx.createBuffer(1,ctx.sampleRate*4,ctx.sampleRate),samples=buffer.getChannelData(0);let smooth=0;for(let i=0;i<samples.length;i++){smooth=.98*smooth+.02*(Math.random()*2-1);samples[i]=smooth*4;}const noise=ctx.createBufferSource(),filter=ctx.createBiquadFilter();noise.buffer=buffer;noise.loop=true;filter.type='lowpass';filter.frequency.value=type==='harbour'?750:type==='room'?280:500;noise.connect(filter).connect(master);noise.start();sources.push(noise);
      const pulse=()=>{if(!master)return;const now=ctx.currentTime;if(type==='tram'){tone(830,now,.6,.12);tone(1240,now+.2,.9,.05);}else if(type==='park'){tone(1650,now,.16,.045);tone(2100,now+.22,.2,.025);}else if(type==='concert'){[220,330,440].forEach((f,i)=>tone(f,now+i*.4,1.4,.035));}else if(type==='harbour')tone(110,now,1.5,.035);};pulse();soundTimer=setInterval(pulse,4500);
    }catch{$('scene-sound-label').textContent='此裝置暫無音效';sound=false;}}
  function hide(smooth=false){const token=++sceneVersion;clearTimeout(hideTimer);open=false;stopSound();const el=$('memory-scene');el.classList.remove('scene-visible');el.inert=true;
    const finish=()=>{if(token!==sceneVersion)return;window.MemoryMorph?.hide();el.hidden=true;el.classList.remove('is-revealed');};
    if(smooth&&!reduced.matches&&!el.hidden)hideTimer=setTimeout(finish,240);else finish();
  }
  function show(stop,force=false){current=stop;$('revisit-scene').disabled=false;if(!enabled&&!force)return;const info=window.MEMORY_SCENES[stop.id];if(!info)return;hide();open=true;const token=sceneVersion,el=$('memory-scene');el.inert=false;el.hidden=false;el.classList.remove('scene-visible');el.classList.remove('is-revealed');$('scene-image').src=info.src;$('scene-image').alt=stop.name+'，回憶場景參考照片';$('scene-backdrop').style.backgroundImage=`url("${info.src}")`;$('scene-place').textContent=stop.name;$('scene-date').textContent='2026.'+stop.date+' · '+stop.time+' / '+stop.with;$('scene-caption').textContent=info.caption;$('scene-note').textContent=info.note;$('scene-context').textContent=info.context;$('scene-credit').textContent='照片 '+info.artist+' · '+info.license;$('scene-credit').href=info.url;$('scene-photo-error').hidden=true;
      $('scene-souvenirs').innerHTML=info.art.map(id=>`<button class="scene-souvenir" data-scene-art="${id}" aria-label="打開${window.ATLAS_TRIP.stickers[id].name}的回憶"><span class="sticker ${id>=9?'interest-art':''}" style="--sx:${id%3*50}%;--sy:${Math.floor(id%9/3)*50}%"></span><span>${window.ATLAS_TRIP.stickers[id].name}</span></button>`).join('');$('scene-note').classList.remove('souvenir-open');$('scene-image').style.transform='';requestAnimationFrame(()=>requestAnimationFrame(()=>{if(token===sceneVersion&&open)el.classList.add('is-revealed','scene-visible');}));playSound();window.MemoryMorph?.show(info);const next=window.MEMORY_SCENES[stop.id+1];if(next){const preload=new Image();preload.src=next.src;}
  }
  $('scene-image').onerror=()=>$('scene-photo-error').hidden=false;
  $('scene-map').onclick=()=>{hide(true);window.dispatchEvent(new Event('memory:pause'));};
  $('scene-stay').onclick=()=>{window.dispatchEvent(new Event('memory:pause'));$('scene-stay').textContent='已停留 · 下方可繼續旅程';};
  $('scene-sound').onclick=()=>{sound=!sound;$('scene-sound').setAttribute('aria-pressed',sound);$('scene-sound-label').textContent=sound?'氛圍音 開':'氛圍音 關';$('scene-sound').querySelector('img').src='assets/icons/'+(sound?'volume-2':'volume-x')+'.svg';playSound();};
  $('scene-auto').onclick=()=>{enabled=!enabled;$('scene-auto').setAttribute('aria-pressed',enabled);$('scene-auto').textContent=enabled?'到站展開回憶 ✓':'到站展開回憶';if(!enabled)hide(true);};
  $('revisit-scene').onclick=()=>{if(current){window.dispatchEvent(new Event('memory:pause'));show(current,true);$('memory-scene').scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'center'});}};
  $('scene-souvenirs').onclick=e=>{const b=e.target.closest('[data-scene-art]');if(!b)return;window.dispatchEvent(new Event('memory:pause'));const a=window.ATLAS_TRIP.stickers[+b.dataset.sceneArt];$('scene-note').textContent='「'+a.name+'」 · '+window.MEMORY_SCENES[current.id].note;$('scene-note').classList.add('souvenir-open');b.classList.toggle('opened');};
  $('memory-scene').addEventListener('pointermove',e=>{if(reduced.matches||e.pointerType==='touch'&&e.buttons===0)return;const r=$('memory-scene').getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;$('scene-image').style.transform=`translate(${x*-14}px,${y*-8}px) scale(1.035)`;});
  $('memory-scene').addEventListener('pointerleave',()=>{$('scene-image').style.transform='';});
  document.addEventListener('visibilitychange',()=>{if(document.hidden)stopSound();});window.addEventListener('pagehide',()=>{stopSound();ctx?.close();ctx=null;sound=false;$('scene-sound').setAttribute('aria-pressed','false');$('scene-sound-label').textContent='氛圍音 關';$('scene-sound').querySelector('img').src='assets/icons/volume-x.svg';});
  window.MemoryScene={show,hide,setOrigin(x,y){const el=$('memory-scene'),w=el.clientWidth||el.parentElement.clientWidth,h=el.clientHeight||el.parentElement.clientHeight;el.style.setProperty('--scene-anchor',`${Math.max(0,Math.min(w,x))}px ${Math.max(0,Math.min(h,y))}px`);},setCurrent(s){current=s;$('revisit-scene').disabled=false;},isOpen:()=>open,isEnabled:()=>enabled,resetStay(){$('scene-stay').textContent='停留在這一刻';}};
})();
