(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const data = window.MOBILE_CONTENT, days = data.days, stops = days.flatMap(d => d.stops);
  const colors = ['#148dba','#d78043','#7461b4','#438e75','#bc596c'];
  const names = ['小安（你）','小宇','小庭','阿哲','小晴','小恩','小凱','小文'];
  const plans = {light:{name:'每日 1GB 高速上網',price:199,range:'2–4',desc:'共 5GB 高速額度 · 每日重置',reason:'導航與聊天為主，照片盡量回飯店再上傳。'},normal:{name:'每日 2GB 高速上網',price:299,range:'5–8',desc:'共 10GB 高速額度 · 每日重置',reason:'照片上傳、導航與社群；住宿有 Wi-Fi。'},heavy:{name:'每日 5GB 高速上網',price:499,range:'15–22',desc:'共 25GB 高速額度 · 每日重置',reason:'影片或熱點使用較多，仍需留意公平使用與熱點限制。'}};
  const state = {page:'trip',day:0,view:'list',spot:0,usage:'normal',members:[{name:names[0],paid:false,price:299}],style:'editorial',generated:false,doc:'canvas',ta:0,storyTa:'all',adjusted:false,flow:0};
  let playing=false,frame=0,wait=0,toastTimer=0,photoUrl='',lastFocus=null;
  const reduced = matchMedia('(prefers-reduced-motion: reduce)');
  const esc = t => String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money = n => n.toLocaleString('zh-TW');
  const paid = () => state.members.filter(m=>m.paid).length;
  function notify(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3000);}
  function openSheet(title,body){lastFocus=document.activeElement;$('sheet-title').textContent=title;$('sheet-body').innerHTML=body;if(!$('sheet').open)$('sheet').showModal();$('sheet-close').focus();}
  function closeSheet(){$('sheet').close();if(lastFocus?.isConnected)lastFocus.focus();}
  $('sheet-close').onclick=closeSheet;
  $('sheet').addEventListener('click',e=>{if(e.target===$('sheet')){const r=$('sheet').getBoundingClientRect();if(e.clientY<r.top||e.clientX<r.left||e.clientX>r.right)closeSheet();}});
  function navigate(){const id=location.hash.slice(1).split('?')[0];state.page=['trip','esim','memory','proposal'].includes(id)?id:'trip';stopPlayback();document.querySelectorAll('.screen').forEach(el=>{el.hidden=el.id!==state.page;el.classList.toggle('active',el.id===state.page);});document.querySelectorAll('.bottom-nav a').forEach(a=>{if(a.hash==='#'+state.page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});if(state.page==='proposal')renderProposal();window.scrollTo(0,0);if(state.page==='trip'&&state.view==='map')requestAnimationFrame(renderMap);}
  window.addEventListener('hashchange',navigate);
  function memberUI(){try{sessionStorage.setItem('chictrip-mobile-members',JSON.stringify(state.members));}catch{}const p=paid();$('avatars').innerHTML=state.members.slice(0,4).map(m=>`<span class="avatar">${esc(m.name.slice(0,1))}</span>`).join('');$('invite').setAttribute('aria-label',`${state.members.length} 人共編，邀請旅伴`);$('deal-caption').textContent=p>=4?'已解鎖旅伴價，每人現省 NT$20':`${p} 人已購買 · 4 人成團，每人現省 NT$20`;$('join-buy').textContent=state.members[0].paid?'已完成我的模擬購買':'模擬我的 eSIM 購買';$('join-buy').disabled=state.members[0].paid;$('memory-eligibility').textContent=state.members[0].paid?(state.generated?'已使用 1 次示範創作；仍可切換風格預覽。':'你已解鎖本趟回憶創作 1 次。'):'本趟 eSIM 購買後，解鎖 1 次創作。';$('create-memory').textContent=state.members[0].paid?'體驗創作流程（示範）':'查看解鎖方式';}
  function inviteSheet(){openSheet('旅伴一起排行程',`<p>${state.members.length} 人共編 · ${paid()} 人已購買 eSIM</p><p class="muted">朋友都能加入共編，購買 eSIM 是各自的選擇。</p>${state.members.map(m=>`<div class="member-row"><span class="avatar">${esc(m.name[0])}</span><span>${esc(m.name)}<small>${m.paid?'已購買 eSIM':'可自由共編'}</small></span><span class="mock">已加入</span></div>`).join('')}<button class="primary" data-action="invite-add" ${state.members.length>=8?'disabled':''}>${state.members.length>=8?'8 位示範旅伴皆已加入':'模擬一位朋友加入'}</button><p class="small-note">僅新增本機示範旅伴，不會傳送真實邀請。</p>`);}
  function dealSheet(){const p=paid(),members=state.members.filter(m=>m.paid),base=members.reduce((n,m)=>n+m.price,0),saving=p>=4?p*20:0;openSheet('旅伴組隊省',`<span class="mock">優惠與價格皆為 Mock</span><p><b>${state.members.length} 人共編</b>，其中 <b>${p} 人購買 eSIM</b></p><div class="group-total"><p>${p>=4?'旅伴價已解鎖':'4 人各自購買，每人現省 NT$20'}</p><strong>${p?'NT$'+money(base-saving):'還沒有人購買'}</strong><small>${p?`${p} 人實付合計${saving?' · 比一般價省 NT$'+saving:''}`:'以每人 NT$299 為例，4 人實付 NT$1,116，合省 NT$80。'}</small></div><div class="unlock-row">${[[2,'＋500MB'],[3,'30 chicCoin'],[4,'現省 NT$20']].map(([n,reward])=>`<div class="${p>=n?'unlocked':''}"><b>${p>=n?'✓ ':''}${n} 人購買</b>${reward}<small style="display:block;margin-top:5px;font-size:10px">每位購買者</small></div>`).join('')}</div><p class="small-note">福利累加；點數不是現金。示範 chicCoin 限下次滿 NT$299 抵用、30 天有效；額外流量限本趟使用。付款人數與共編人數分開計算。</p>${state.members.map((m,i)=>`<div class="member-row"><span class="avatar">${esc(m.name[0])}</span><span>${esc(m.name)}<small>${m.paid?'一般價 NT$'+m.price:'尚未購買'}</small></span><button data-buy="${i}" ${m.paid?'disabled':''}>${m.paid?'已購買':'模擬購買'}</button></div>`).join('')}<button class="secondary" data-action="invite-sheet" style="margin-top:16px">邀請更多旅伴共編</button><p class="small-note">原型以成團後重算優惠示範；實際收款與成團退款規則待確認。不會建立真實訂單。</p>`);}
  function buy(index){if(state.members[index].paid)return;state.members[index].paid=true;state.members[index].price=index===0?plans[state.usage].price:299;memberUI();notify(paid()===4?'4 人購買，已解鎖每人 NT$20 旅伴折扣':'已完成示範購買');}
  const shownStops=()=>state.day===-1?stops:days[state.day].stops;
  function renderDays(){$('day-bar').innerHTML=`<button data-day="-1" aria-pressed="${state.day===-1}"><strong>全程</strong>5 天</button>`+days.map((d,i)=>`<button data-day="${i}" style="--day:${colors[i]}" aria-pressed="${state.day===i}"><strong>第 ${i+1} 天</strong><span class="day-dot"></span>10/${12+i}</button>`).join('');}
  function renderTrip(){renderDays();$('area-title').textContent=state.day===-1?'東京 5 日全程':days[state.day].area;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===state.view));$('list-view').hidden=state.view!=='list';$('map-view').hidden=state.view!=='map';const list=shownStops();$('list-view').innerHTML=list.map((s,i)=>`<article class="stop-row" style="--day:${colors[s.day]}"><div class="stop-track"><span class="stop-number">${state.day===-1?i+1:i+1}</span></div><button class="stop-card" data-stop="${s.id}"><div><time>第 ${s.day+1} 天 · ${s.time}</time><h3>${esc(s.name)}</h3><p>${esc(s.note)}</p><small>${esc(s.stay)} · 看詳情 ›</small></div><img src="${s.photo.src}" alt="${esc(s.name)}實景" loading="lazy" style="object-position:${s.photo.objectPosition}"></button></article>`).join('');if(state.view==='map')requestAnimationFrame(renderMap);}
  function spotHTML(s){return `<img class="spot-photo" src="${s.photo.src}" alt="${esc(s.name)}實景" style="object-position:${s.photo.objectPosition}"><h3>第 ${s.day+1} 天 · ${esc(s.name)}</h3><p>${esc(s.note)}</p><div class="estimate"><span>本站預估用量<br><small>${esc(s.stay)}</small></span><strong>${s.range.join('–')} <small>MB / 人</small></strong></div><p class="small-note">Mock：導航、查詢與照片分享的使用情境；非現場即時用量。影片與熱點會增加需求。</p><a class="photo-credit" href="${s.photo.source}" target="_blank" rel="noopener">實景照片：${esc(s.photo.credit)} · ${esc(s.photo.license)} ↗</a>`;}
  let mapPoints=[],project=null,routeContext=null,mapW=0,mapH=0;
  function renderMap(){if(state.page!=='trip'||state.view!=='map')return;const box=$('route-map');mapW=box.clientWidth;mapH=box.clientHeight;if(!mapW)return;const selected=shownStops(),coords=selected.map(s=>s.at);const xs=coords.map(p=>p[0]),ys=coords.map(p=>p[1]);const midX=(Math.min(...xs)+Math.max(...xs))/2,midY=(Math.min(...ys)+Math.max(...ys))/2;let sx=Math.max(.003,Math.max(...xs)-Math.min(...xs))*1.5,sy=Math.max(.003,Math.max(...ys)-Math.min(...ys))*1.6;const aspect=mapW/mapH/.812;if(sx/sy<aspect)sx=sy*aspect;else sy=sx/aspect;project=([x,y])=>[(x-midX)/sx*mapW+mapW/2,(midY-y)/sy*mapH+mapH/2];const dpr=Math.min(devicePixelRatio||1,2);for(const c of [$('base-map'),$('route-layer')]){c.width=mapW*dpr;c.height=mapH*dpr;c.getContext('2d').setTransform(dpr,0,0,dpr,0,0);}const ctx=$('base-map').getContext('2d');routeContext=$('route-layer').getContext('2d');ctx.fillStyle='#edf1e9';ctx.fillRect(0,0,mapW,mapH);const drawPath=(points)=>{ctx.beginPath();points.forEach((p,i)=>{const q=project(p);i?ctx.lineTo(...q):ctx.moveTo(...q);});};const base=window.TOKYO_MAP_DATA;if(base){ctx.fillStyle='#dbe8d6';base.parks.forEach(f=>{drawPath(f.points);ctx.fill();});ctx.fillStyle='#cce8f2';ctx.strokeStyle='#cce8f2';ctx.lineWidth=9;base.water.forEach(f=>{drawPath(f.points);f.closed?ctx.fill():ctx.stroke();});ctx.strokeStyle='white';ctx.lineWidth=2;base.roads.forEach(f=>{drawPath(f.points);ctx.stroke();});ctx.strokeStyle='#bfcbc2';ctx.lineWidth=.7;ctx.setLineDash([3,4]);base.rail.forEach(f=>{drawPath(f.points);ctx.stroke();});ctx.setLineDash([]);}
    mapPoints=selected.map(s=>({...s,p:project(s.at)}));drawRoute();const pins=state.day===-1?[[0,4],[1,3],[2]].map(group=>({s:days[group[0]].stops[0],p:project(group.reduce((a,i)=>[a[0]+days[i].stops[0].at[0]/group.length,a[1]+days[i].stops[0].at[1]/group.length],[0,0])),label:group.map(i=>i+1).join('·'),group})):mapPoints.map((s,i)=>({s,p:s.p,label:String(i+1)}));$('map-pins').innerHTML=pins.map(p=>`<button class="map-pin" style="left:${p.p[0]}px;top:${p.p[1]}px;--day:${colors[p.s.day]}" ${state.day===-1?`data-cluster="${p.group.join(',')}"`:`data-map-stop="${p.s.id}"`} aria-pressed="${state.day!==-1&&p.s.id===state.spot}" aria-label="${state.day===-1?'查看第 '+p.group.map(i=>i+1).join('、')+' 天的行程':p.label+' '+p.s.name}"><span style="${p.group?.length>1?'width:36px;border-radius:14px;background:#28576e':''}">${p.label}</span></button>`).join('');$('map-stops').innerHTML=state.day===-1?days.map((d,i)=>`<button data-day="${i}"><b>第 ${i+1} 天</b><small>${esc(d.area)} · 3 站</small></button>`).join(''):selected.map((s,i)=>`<button data-map-stop="${s.id}" aria-pressed="${s.id===state.spot}"><b>${i+1} ${esc(s.name)}</b><small>第 ${s.day+1} 天 · ${s.time}</small></button>`).join('');$('stop-status').textContent=state.day===-1?'點選日子展開景點':`${selected.findIndex(s=>s.id===state.spot)+1} / ${selected.length} 站`;$('play').disabled=state.day===-1;$('next-stop').disabled=state.day===-1;$('spot-detail').innerHTML=state.day===-1?'<p class="page-note">各色實線為單日行程，虛線為日間移動。選一天，看每站照片與流量。</p>':`<article class="spot-info">${spotHTML(stops[state.spot])}</article>`;
  }
  function drawRoute(traveler){if(!routeContext||!mapPoints.length)return;const ctx=routeContext;ctx.clearRect(0,0,mapW,mapH);ctx.lineWidth=3;ctx.lineCap='round';for(let i=1;i<mapPoints.length;i++){const a=mapPoints[i-1],b=mapPoints[i];ctx.beginPath();ctx.moveTo(...a.p);ctx.lineTo(...b.p);ctx.strokeStyle=colors[b.day];ctx.setLineDash(a.day===b.day?[]:[4,6]);ctx.stroke();}ctx.setLineDash([]);if(traveler){ctx.beginPath();ctx.arc(...traveler,7,0,Math.PI*2);ctx.fillStyle='#16364c';ctx.fill();ctx.lineWidth=3;ctx.strokeStyle='#ffd83e';ctx.stroke();}}
  function stopPlayback(){playing=false;cancelAnimationFrame(frame);clearTimeout(wait);$('play').textContent='播放旅程';}
  function nextStop(auto=false){const list=shownStops();if(state.day===-1)return;const current=Math.max(0,list.findIndex(s=>s.id===state.spot)),next=(current+1)%list.length;const from=project(list[current].at),to=project(list[next].at);if(!auto)stopPlayback();const start=performance.now();function tick(now){const t=reduced.matches?1:Math.min(1,(now-start)/1100),u=t*t*(3-2*t);drawRoute([from[0]+(to[0]-from[0])*u,from[1]+(to[1]-from[1])*u]);if(t<1)frame=requestAnimationFrame(tick);else{state.spot=list[next].id;renderMap();if(auto&&playing){if(next===list.length-1)stopPlayback();else wait=setTimeout(()=>nextStop(true),2000);}}}frame=requestAnimationFrame(tick);}
  function renderUsage(){const plan=plans[state.usage];$('trip-usage').innerHTML=plan.range+' <small>GB</small>';$('usage-reason').textContent=plan.reason;$('plan-name').textContent=plan.name;$('plan-description').textContent=plan.desc;$('plan-price').textContent=plan.price;document.querySelectorAll('[data-usage]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.usage===state.usage));$('plan-label').textContent=state.members[0].paid?'模擬選購已完成，可比較其他規格':'依你的習慣推薦';}
  function adjustSheet(){stopPlayback();openSheet('臨時改行程',`<p>示範：第 1 天遇到下雨，想把戶外散步換成室內參觀。</p><label><input id="lock-plan" type="checkbox" checked> 保留淺草寺與晴空塔，不動已確定的安排</label><textarea id="adjust-text" aria-label="改程需求" maxlength="200" placeholder="例如：下雨了，將隅田公園改成室內景點。"></textarea><p class="small-note">這裡示範一組預設替換；正式版才會用 AI 理解自由輸入。</p><button class="primary" data-action="adjust-preview">看調整前後</button>`);}
  let previousStop=null;
  function savedPlan(){let saved;try{saved=JSON.parse(localStorage.getItem('chictrip-circle-planner-v1'))?.saved;}catch{}openSheet('圈選排程 · 已儲存',saved?.stops?`<p>來自你在圈選排程頁儲存的草案。</p>${saved.stops.map(s=>`<div class="member-row"><time>${esc(s.time)}</time><strong>${esc(s.name)}</strong></div>`).join('')}<p class="small-note">這份草案獨立保存；東京 5 日行程仍為原始示範。</p><a class="primary" href="../circle-trip-planner/index.html?mobile=1">繼續編輯</a>`:'<p>還沒有儲存圈選行程。先圈選想去的區域，輸入偏好後預覽並保存。</p><a class="primary" href="../circle-trip-planner/index.html?mobile=1">開始圈選排程</a>');}
  function renderProposal(){document.querySelectorAll('[data-doc]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.doc===state.doc));if(state.doc==='canvas'){const c=data.canvases[state.ta];$('proposal-content').innerHTML=`<div class="audience-select"><label for="canvas-ta">選一個使用情境</label><select id="canvas-ta">${data.canvases.map((v,i)=>`<option value="${i}" ${i===state.ta?'selected':''}>${v.number} ${esc(v.ta)}${i===3?' · 分享者':i===4?' · 觀看者':''}</option>`).join('')}</select></div><div class="panel"><span class="tag">需求與價值均為待驗證假設</span><p class="promise">${esc(c.promise)}</p><p class="muted">${esc(c.scenario)}</p></div><div class="panel"><h2>使用者想完成什麼？</h2>${[['任務',c.jobs],['痛點',c.pains],['期待收穫',c.gains]].map(([title,items])=>`<div class="canvas-group"><h3>${title}</h3><ol>${items.map(t=>`<li>${esc(t)}</li>`).join('')}</ol></div>`).join('')}</div><div class="panel"><h2>我們提供的價值</h2>${[['產品與服務',c.services],['如何減輕痛點',c.relievers],['如何創造收穫',c.creators]].map(([title,items])=>`<div class="canvas-group"><h3>${title}</h3><ol>${items.map(t=>`<li>${esc(t)}</li>`).join('')}</ol></div>`).join('')}</div><details class="panel"><summary>如何驗證？與 eSIM 有什麼關係？</summary><p>${esc(c.fit)}</p><p>${esc(c.test)}</p><p>${esc(c.business)}</p>${c.assumptions.map(s=>`<p class="small-note">${esc(s)}</p>`).join('')}</details><p class="page-note">框架參考 <a href="https://www.strategyzer.com/library/the-value-proposition-canvas" target="_blank" rel="noopener">Strategyzer Value Proposition Canvas ↗</a></p>`;}
    else if(state.doc==='stories'){const items=data.stories.stories.filter(s=>state.storyTa==='all'||s.audience===state.storyTa);$('proposal-content').innerHTML=`<div class="audience-select"><label for="story-ta">依 TA 篩選 · ${items.length} 則故事</label><select id="story-ta"><option value="all">全部 TA</option>${data.stories.audiences.map(a=>`<option value="${a.id}" ${state.storyTa===a.id?'selected':''}>${esc(a.title)}</option>`).join('')}</select></div><p class="page-note">As a / I want / So that；驗收以 Given / When / Then 撰寫。這是規格草案，不表示已通過驗收。</p>${items.map(s=>`<details class="story-card"><summary><span><small>${s.id} · ${esc(s.priority)}</small>${esc(s.title)}</span></summary><div class="story-sentence"><b>身為</b> ${esc(s.role)}，<br><b>我想要</b> ${esc(s.want)}，<br><b>以便</b> ${esc(s.benefit)}。</div><p class="metric">${esc(s.context)}</p>${s.scenarios.map(a=>`<section class="acceptance"><h3>${a.id} · ${esc(a.title)} <span class="mock">${esc(a.kind)}</span></h3><dl><dt>Given · 前提</dt><dd>${esc(a.given)}</dd><dt>When · 操作</dt><dd>${esc(a.when)}</dd><dt>Then · 預期結果</dt><dd>${esc(a.then)}</dd></dl></section>`).join('')}<section class="acceptance"><h3>例外處理</h3><p class="metric">${esc(s.exception)}</p><h3>邊界條件</h3><p class="metric">${esc(s.boundary)}</p></section><p class="metric">量測：${esc(s.metric)}</p><div class="canvas-group"><h3>業務規則</h3><ol>${s.rules.map(r=>`<li>${esc(r)}</li>`).join('')}</ol></div></details>`).join('')}`;
    } else renderBusiness();
  }
  function renderBusiness(){$('proposal-content').innerHTML=`<div class="panel"><div class="row"><h2>每趟旅行的貢獻毛利</h2><span class="mock">Mock Data</span></div><p class="muted">少一點單張毛利，換取整團訂單的機會。</p>${[['一般購買',80,1/3],['4 人組隊',240,1]].map(([label,n,scale])=>`<div class="bar-row"><div class="bar-label"><span>${label}</span><b>NT$<span data-count="${n}">0</span></b></div><div class="bar-track" style="width:${scale*100}%"><div class="bar-fill"></div></div></div>`).join('')}<table class="stats-table"><thead><tr><th>比較項目</th><th>一般</th><th>組隊</th></tr></thead><tbody><tr><td>eSIM 訂單</td><td>1 張</td><td>4 張</td></tr><tr><td>單張貢獻毛利</td><td>NT$80</td><td>NT$60</td></tr><tr><td>新增使用者</td><td>0 人</td><td>3 人</td></tr></tbody></table><p class="small-note">簡化試算先扣每張 NT$20 折扣；額外流量、點數兌換與生圖成本尚未計入，不能當成淨利預測。新用戶須以實際啟用量測，非邀請即算。</p></div><div class="panel"><h2>轉換從一份行程開始</h2><div id="conversion-flow"></div><button class="secondary" id="flow-next">下一步</button></div><div class="panel"><h2>雙方都得到什麼？</h2><div class="canvas-group"><h3>消費者</h3><p>看得懂實付差額；朋友自由共編，購買後獲得上網優惠與回憶創作。</p></div><div class="canvas-group"><h3>去趣</h3><p>提高行程到 eSIM 的購買機會，透過旅伴與分享接觸新用戶。</p></div><p class="small-note">需對照「原本 4 人也會購買」的情境，量測增量訂單、獎勵成本及回訪，不能只比較 1 張與 4 張。</p></div>`;renderFlow();document.querySelectorAll('[data-count]').forEach(el=>{const to=+el.dataset.count,start=performance.now();function tick(now){const t=reduced.matches?1:Math.min(1,(now-start)/650);el.textContent=Math.round(to*t);if(t<1&&el.isConnected)requestAnimationFrame(tick);}requestAnimationFrame(tick);});}
  function renderFlow(){const steps=[['建立行程','有出遊意圖，開始準備'],['邀旅伴共編','朋友一起加入規劃'],['個別選購 eSIM','購買人數決定福利'],['解鎖回憶創作','使用者自行決定是否分享'],['朋友找到靈感','進入自己的行程，再量測啟用']];$('conversion-flow').innerHTML=steps.map(([title,sub],i)=>`<div class="flow-node ${i<=state.flow?'current':''}"><span>${i+1}</span><div><strong>${title}</strong><p>${sub}</p></div></div>`).join('');$('flow-next').textContent=state.flow===4?'重新播放':'下一步';}
  function friendSheet(){openSheet('從朋友的東京，開始你的旅行',`<div class="friend-card"><img src="assets/photos/sensoji.jpg" alt="朋友分享的淺草旅行示意"><h3>小安的東京散步</h3><p>公開景點：淺草寺、隅田公園、東京晴空塔。</p></div><p class="small-note">觀看者只看到同意公開的地點，不含住宿、旅伴資料或即時位置。示範不會發布社群貼文。</p><button class="primary" data-action="save-inspiration">收藏這 3 個公開景點</button>`);}
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
    if(b.dataset.day!==undefined){if($('sheet').open)closeSheet();stopPlayback();state.day=+b.dataset.day;state.spot=state.day<0?0:state.day*3;renderTrip();}
    else if(b.dataset.cluster){const group=b.dataset.cluster.split(',').map(Number);if(group.length===1){state.day=group[0];state.spot=state.day*3;stopPlayback();renderTrip();}else openSheet('這一帶的行程',group.map(i=>`<button class="link-row" data-day="${i}">第 ${i+1} 天 · ${esc(days[i].area)}<span>查看 3 個景點 ›</span></button>`).join('')+'<p class="small-note">總覽合併鄰近區域，展開單日後會顯示各景點的實際位置。</p>');}
    else if(b.dataset.view){stopPlayback();state.view=b.dataset.view;renderTrip();}
    else if(b.dataset.stop){openSheet(stops[+b.dataset.stop].name,spotHTML(stops[+b.dataset.stop]));}
    else if(b.dataset.mapStop!==undefined){stopPlayback();state.spot=+b.dataset.mapStop;renderMap();}
    else if(b.dataset.buy!==undefined){buy(+b.dataset.buy);dealSheet();}
    else if(b.dataset.usage){state.usage=b.dataset.usage;renderUsage();}
    else if(b.dataset.doc){state.doc=b.dataset.doc;renderProposal();}
    else if(b.id==='invite'||b.dataset.action==='invite-sheet')inviteSheet();
    else if(b.dataset.action==='invite-add'){state.members.push({name:names[state.members.length],paid:false,price:299});memberUI();inviteSheet();notify('旅伴已加入共編，尚未購買 eSIM');}
    else if(['deal-open','esim-group'].includes(b.id))dealSheet();
    else if(b.id==='join-buy'){buy(0);renderUsage();}
    else if(b.id==='play'){if(playing)stopPlayback();else{playing=true;$('play').textContent='暫停';nextStop(true);}}
    else if(b.id==='next-stop')nextStop();
    else if(b.id==='help')openSheet('關於這個手機原型','<p>依去趣官方網站與 App Store 公開介面，參考藍白配色、照片卡片與行程操作，製作的競賽概念原型。</p><p>新增 AI、組隊與回憶功能均為提案模擬，非官方已上線功能；不會付款、邀請或發文。</p><p><a href="https://www.chictrip.com.tw/" target="_blank" rel="noopener">去趣官網 ↗</a></p><p><a href="assets/PHOTO-LICENSE.md" target="_blank">景點照片來源與授權 ↗</a></p><p><a href="assets/MAP-LICENSE.md" target="_blank">離線地圖資料與授權 ↗</a></p><button class="secondary" data-action="reset-group">重設組隊模擬</button>');
    else if(b.dataset.action==='reset-group'){state.members=[{name:names[0],paid:false,price:299}];state.generated=false;memberUI();renderUsage();closeSheet();notify('組隊模擬已重設為 1 人共編、0 人購買');}
    else if(b.id==='trip-info')openSheet('東京 5 日行程','<p>10/12–10/16 · 示範旅行日期</p><p>淺草 → 原宿 → 舞濱 → 新宿 → 上野</p><p class="small-note">景點資訊與停留時間是展示資料，出發前需另行確認。</p>');
    else if(b.id==='saved-plan')savedPlan();
    else if(b.id==='adjust-open')adjustSheet();
    else if(b.dataset.action==='adjust-preview'){if(!$('lock-plan').checked){notify('此示範請保留鎖定安排，再比較局部變更');return;}const text=$('adjust-text').value.trim();if(!text){notify('請先輸入改程需求');$('adjust-text').focus();return;}if(!/下雨|雨天|室內/.test(text)){notify('這組示範支援雨天室內替換，請加入「下雨」或「室內」');return;}openSheet('只換一站，其他照舊',`<div class="change-pair"><div><small>原本</small><strong>12:00 隅田公園</strong></div><div><small>替換草案</small><strong>12:00 東京國立博物館</strong></div></div><p>保留 10:00 淺草寺與 14:00 晴空塔。實際交通與營業時間待確認。</p><button class="primary" data-action="apply-adjust">套用示範替換</button><button class="secondary" data-action="cancel-sheet" style="margin-top:10px">保留原行程</button>`);}
    else if(b.dataset.action==='apply-adjust'){stopPlayback();if(!state.adjusted)previousStop=JSON.parse(JSON.stringify(stops[1]));const replacement=stops[12];Object.assign(stops[1],replacement,{id:1,day:0,time:'12:00',stay:'停留 45 分鐘',note:'雨天替代：室內展覽，交通與開館時間待查核'});state.adjusted=true;state.day=0;state.spot=1;renderTrip();openSheet('已套用局部替換','<p>只替換第 1 天的隅田公園，其餘安排保留。</p><button class="secondary" data-action="undo-adjust">復原這次調整</button>');}
    else if(b.dataset.action==='undo-adjust'&&previousStop){stopPlayback();Object.assign(stops[1],previousStop);previousStop=null;state.adjusted=false;renderTrip();closeSheet();notify('已回到原本的隅田公園');}
    else if(b.dataset.action==='cancel-sheet')closeSheet();
    else if(b.id==='friend-view')friendSheet();
    else if(b.dataset.action==='save-inspiration'){try{localStorage.setItem('chictrip-mobile-inspiration',JSON.stringify([0,1,2]));}catch{}openSheet('已收藏 3 個公開景點','<p>這份靈感屬於你；朋友原本的旅行不會被更動。</p><a class="primary" href="../circle-trip-planner/index.html?mobile=1&inspiration=east">用這些景點規劃自己的旅行</a>');}
    else if(b.id==='flow-next'){state.flow=(state.flow+1)%5;renderFlow();}
  });
  document.addEventListener('change',e=>{if(e.target.id==='canvas-ta'){state.ta=+e.target.value;renderProposal();}else if(e.target.id==='story-ta'){state.storyTa=e.target.value;renderProposal();}});
  $('unused').addEventListener('input',e=>{const n=+e.target.value;$('unused-value').textContent=n+' GB';$('chip-value').textContent=Math.min(30,n*10);});
  new ResizeObserver(()=>{if(state.view==='map'){stopPlayback();renderMap();}}).observe($('route-map'));
  try{const cached=JSON.parse(sessionStorage.getItem('chictrip-mobile-members'));if(Array.isArray(cached)&&cached.length>0&&cached.length<=8&&cached.every(m=>typeof m.name==='string'&&typeof m.paid==='boolean'&&[199,299,499].includes(m.price)))state.members=cached;}catch{}
  window.ChicMemoryAccess={isEligible:()=>state.members[0].paid,notify};
  memberUI();renderUsage();renderTrip();navigate();
})();
